// <auto-generated />
using System;
using LINQToQuery.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LINQToQuery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231126090637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6882),
                            FirstName = "Michelle",
                            LastName = "Alexander",
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6885),
                            FirstName = "Stephen E.",
                            LastName = "Ambrose",
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6886),
                            FirstName = "Margaret",
                            LastName = "Atwood",
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6887),
                            FirstName = "Jane",
                            LastName = "Austen",
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6888),
                            FirstName = "James",
                            LastName = "Baldwin",
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6889),
                            FirstName = "Emily",
                            LastName = "Bronte",
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6890),
                            FirstName = "Agatha",
                            LastName = "Christie",
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6891),
                            FirstName = "Ta-Nehisi",
                            LastName = "Coates",
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6892),
                            FirstName = "Jared",
                            LastName = "Diamond",
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6893),
                            FirstName = "Joa",
                            LastName = "Didion",
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6894),
                            FirstName = "Daphne",
                            LastName = "Du Maurier",
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6895),
                            FirstName = "Tina",
                            LastName = "Fey",
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6896),
                            FirstName = "Roxane",
                            LastName = "Gay",
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6897),
                            FirstName = "Dashiel",
                            LastName = "Hammett",
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6898),
                            FirstName = "Frank",
                            LastName = "Herbert",
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6899),
                            FirstName = "Aldous",
                            LastName = "Huxley",
                            Status = 1
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6900),
                            FirstName = "Stieg",
                            LastName = "Larsson",
                            Status = 1
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6901),
                            FirstName = "David",
                            LastName = "McCullogh",
                            Status = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6902),
                            FirstName = "Toni",
                            LastName = "Morrison",
                            Status = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6903),
                            FirstName = "George",
                            LastName = "Orwell",
                            Status = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6904),
                            FirstName = "Mary",
                            LastName = "Shelley",
                            Status = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6904),
                            FirstName = "Sun",
                            LastName = "Tzu",
                            Status = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6905),
                            FirstName = "Augusten",
                            LastName = "Burroughs",
                            Status = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6907),
                            FirstName = "JK",
                            LastName = "Rowling",
                            Status = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6908),
                            FirstName = "Seth",
                            LastName = "Grahame-Smith",
                            Status = 1
                        });
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenreId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6515),
                            GenreId = "history",
                            Price = 18.0,
                            Status = 1,
                            Title = "1776"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6519),
                            GenreId = "scifi",
                            Price = 5.5,
                            Status = 1,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6521),
                            GenreId = "mystery",
                            Price = 4.5,
                            Status = 1,
                            Title = "And Then There Were None"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6522),
                            GenreId = "history",
                            Price = 11.5,
                            Status = 1,
                            Title = "Band of Brothers"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6523),
                            GenreId = "novel",
                            Price = 10.99,
                            Status = 1,
                            Title = "Beloved"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6525),
                            GenreId = "memoir",
                            Price = 13.5,
                            Status = 1,
                            Title = "Between The World And Me"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6526),
                            GenreId = "memoir",
                            Price = 4.25,
                            Status = 1,
                            Title = "Bossypants"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6566),
                            GenreId = "scifi",
                            Price = 16.25,
                            Status = 1,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6567),
                            GenreId = "history",
                            Price = 15.0,
                            Status = 1,
                            Title = "D-Day"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6569),
                            GenreId = "memoir",
                            Price = 4.25,
                            Status = 1,
                            Title = "Down and Out in Paris and London"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6570),
                            GenreId = "scifi",
                            Price = 8.75,
                            Status = 1,
                            Title = "Dune"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6571),
                            GenreId = "novel",
                            Price = 9.0,
                            Status = 1,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 13,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6572),
                            GenreId = "scifi",
                            Price = 6.5,
                            Status = 1,
                            Title = "Frankestein"
                        },
                        new
                        {
                            Id = 14,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6573),
                            GenreId = "novel",
                            Price = 10.25,
                            Status = 1,
                            Title = "Go Tell It On The Mountain"
                        },
                        new
                        {
                            Id = 15,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6574),
                            GenreId = "history",
                            Price = 15.5,
                            Status = 1,
                            Title = "Guns, Germs and Steel"
                        },
                        new
                        {
                            Id = 16,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6575),
                            GenreId = "memoir",
                            Price = 14.5,
                            Status = 1,
                            Title = "Hunger"
                        },
                        new
                        {
                            Id = 17,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6576),
                            GenreId = "mystery",
                            Price = 6.75,
                            Status = 1,
                            Title = "Murder on the Orient Express"
                        },
                        new
                        {
                            Id = 18,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6577),
                            GenreId = "novel",
                            Price = 8.5,
                            Status = 1,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 19,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6578),
                            GenreId = "mystery",
                            Price = 10.99,
                            Status = 1,
                            Title = "Rebecca"
                        },
                        new
                        {
                            Id = 20,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6580),
                            GenreId = "history",
                            Price = 5.75,
                            Status = 1,
                            Title = "The Art of War"
                        },
                        new
                        {
                            Id = 21,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6581),
                            GenreId = "mystery",
                            Price = 8.5,
                            Status = 1,
                            Title = "The Girl With The Dragon Tattoo"
                        },
                        new
                        {
                            Id = 22,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6582),
                            GenreId = "scifi",
                            Price = 12.5,
                            Status = 1,
                            Title = "The Handmaid's Tale"
                        },
                        new
                        {
                            Id = 23,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6583),
                            GenreId = "mystery",
                            Price = 10.99,
                            Status = 1,
                            Title = "The Maltese Falcon"
                        },
                        new
                        {
                            Id = 24,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6584),
                            GenreId = "history",
                            Price = 13.75,
                            Status = 1,
                            Title = "The New Jim Crow"
                        },
                        new
                        {
                            Id = 25,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6585),
                            GenreId = "memoir",
                            Price = 13.5,
                            Status = 1,
                            Title = "The Year of Magical Thinking"
                        },
                        new
                        {
                            Id = 26,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6586),
                            GenreId = "novel",
                            Price = 9.0,
                            Status = 1,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 27,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6587),
                            GenreId = "memoir",
                            Price = 11.0,
                            Status = 1,
                            Title = "Running With Scissors"
                        },
                        new
                        {
                            Id = 28,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6588),
                            GenreId = "novel",
                            Price = 8.75,
                            Status = 1,
                            Title = "Pride and Prejudice and Zombies"
                        },
                        new
                        {
                            Id = 29,
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6589),
                            GenreId = "novel",
                            Price = 9.75,
                            Status = 1,
                            Title = "Harry Potter and The Sorcerer's Stone"
                        });
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.BookAuthor", b =>
                {
                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            AuthorId = 18,
                            BookId = 1
                        },
                        new
                        {
                            AuthorId = 20,
                            BookId = 2
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 3
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 4
                        },
                        new
                        {
                            AuthorId = 19,
                            BookId = 5
                        },
                        new
                        {
                            AuthorId = 8,
                            BookId = 6
                        },
                        new
                        {
                            AuthorId = 12,
                            BookId = 7
                        },
                        new
                        {
                            AuthorId = 16,
                            BookId = 8
                        },
                        new
                        {
                            AuthorId = 2,
                            BookId = 9
                        },
                        new
                        {
                            AuthorId = 20,
                            BookId = 10
                        },
                        new
                        {
                            AuthorId = 15,
                            BookId = 11
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 12
                        },
                        new
                        {
                            AuthorId = 21,
                            BookId = 13
                        },
                        new
                        {
                            AuthorId = 5,
                            BookId = 14
                        },
                        new
                        {
                            AuthorId = 9,
                            BookId = 15
                        },
                        new
                        {
                            AuthorId = 13,
                            BookId = 16
                        },
                        new
                        {
                            AuthorId = 7,
                            BookId = 17
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 18
                        },
                        new
                        {
                            AuthorId = 11,
                            BookId = 19
                        },
                        new
                        {
                            AuthorId = 22,
                            BookId = 20
                        },
                        new
                        {
                            AuthorId = 17,
                            BookId = 21
                        },
                        new
                        {
                            AuthorId = 3,
                            BookId = 22
                        },
                        new
                        {
                            AuthorId = 14,
                            BookId = 23
                        },
                        new
                        {
                            AuthorId = 1,
                            BookId = 24
                        },
                        new
                        {
                            AuthorId = 10,
                            BookId = 25
                        },
                        new
                        {
                            AuthorId = 6,
                            BookId = 26
                        },
                        new
                        {
                            AuthorId = 23,
                            BookId = 27
                        },
                        new
                        {
                            AuthorId = 4,
                            BookId = 28
                        },
                        new
                        {
                            AuthorId = 26,
                            BookId = 28
                        },
                        new
                        {
                            AuthorId = 25,
                            BookId = 29
                        });
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Genre", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = "novel",
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6118),
                            Name = "Novel",
                            Status = 1
                        },
                        new
                        {
                            Id = "memoir",
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6130),
                            Name = "Memoir",
                            Status = 1
                        },
                        new
                        {
                            Id = "mystery",
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6131),
                            Name = "Mystery",
                            Status = 1
                        },
                        new
                        {
                            Id = "scifi",
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6132),
                            Name = "Science Finction",
                            Status = 1
                        },
                        new
                        {
                            Id = "history",
                            CreatedDate = new DateTime(2023, 11, 26, 12, 6, 37, 174, DateTimeKind.Local).AddTicks(6133),
                            Name = "History",
                            Status = 1
                        });
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Book", b =>
                {
                    b.HasOne("LINQToQuery.Models.Concrete.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.BookAuthor", b =>
                {
                    b.HasOne("LINQToQuery.Models.Concrete.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LINQToQuery.Models.Concrete.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Book", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("LINQToQuery.Models.Concrete.Genre", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
